apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque # default for arbitrary key-value pairs
data:
  # values must be base64 encoded
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=