apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
    app: nginx
# specification for the deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  # blueprint for pods
  template:
    metadata:
      labels:
        app: nginx
    # specification for the pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
